const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Behaviors.Anchor,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Timeline.Acts.PlayTimeline
	];
};
self.C3_JsPropNameTable = [
	{DashCooldown: 0},
	{DashInertia: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Bullet: 0},
	{Timer: 0},
	{Szeth: 0},
	{Keyboard: 0},
	{"3DCamera": 0},
	{Slash: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Solid: 0},
	{SolidTile: 0},
	{Sine: 0},
	{MovingSolidTile: 0},
	{Jumpthru: 0},
	{JumpThruTile: 0},
	{Tutorial: 0},
	{TiledBackground: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{Balloon: 0},
	{Physics: 0},
	{Sphere: 0},
	{Anchor: 0},
	{SphereMeter: 0},
	{HealthCount: 0},
	{Direction: 0},
	{MoveType: 0},
	{Enemy: 0},
	{EnemyRange: 0},
	{EnemyAttackRange: 0},
	{EnemyAttack: 0},
	{SzethBox: 0},
	{SzethHealth: 0},
	{Spikes: 0},
	{Sprite: 0},
	{Crown: 0},
	{TimelineController: 0},
	{SphereCount: 0},
	{SphereCollision: 0},
	{Lashing: 0}
];

self.InstanceType = {
	Szeth: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	Slash: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	SolidTile: class extends self.ITiledBackgroundInstance {},
	MovingSolidTile: class extends self.ITiledBackgroundInstance {},
	JumpThruTile: class extends self.ITiledBackgroundInstance {},
	Tutorial: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Balloon: class extends self.ISpriteInstance {},
	Sphere: class extends self.ISpriteInstance {},
	SphereMeter: class extends self.ISpriteInstance {},
	HealthCount: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyRange: class extends self.ISpriteInstance {},
	EnemyAttackRange: class extends self.ISpriteInstance {},
	EnemyAttack: class extends self.ISpriteInstance {},
	SzethBox: class extends self.ISpriteInstance {},
	SzethHealth: class extends self.ISpriteInstance {},
	Spikes: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Crown: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {}
}